In [32]:
import pandas as pd

In [33]:
dic = {"name": ["Ronaldo", "Messi"],
       "country": ["Portugal", "Argentina"],
       "Position": ["Striker","Striker"]}

In [34]:
dic

{'name': ['Ronaldo', 'Messi'],
 'country': ['Portugal', 'Argentina'],
 'Position': ['Striker', 'Striker']}

In [35]:
df = pd.Series(dic)
df

name             [Ronaldo, Messi]
country     [Portugal, Argentina]
Position       [Striker, Striker]
dtype: object

In [36]:
type(df)

pandas.Series

In [37]:
df.info

<bound method Series.info of name             [Ronaldo, Messi]
country     [Portugal, Argentina]
Position       [Striker, Striker]
dtype: object>

In [38]:
df.shape

(3,)

In [39]:
df1 = pd.DataFrame(dic)
df1

      name    country Position
0  Ronaldo   Portugal  Striker
1    Messi  Argentina  Striker

In [40]:
df

name             [Ronaldo, Messi]
country     [Portugal, Argentina]
Position       [Striker, Striker]
dtype: object

In [41]:
a = [["joshim","actor","lottery","emotional", 70],["kancon","funny","vitamin","real", 50],["bappa raj","cheka","","classic"]]

In [42]:
df2 = pd.Series(a)

In [43]:
df2

0    [joshim, actor, lottery, emotional, 70]
1         [kancon, funny, vitamin, real, 50]
2              [bappa raj, cheka, , classic]
dtype: object

In [44]:
df3 = pd.DataFrame(a, columns=["Name", "rolls", "luck", "scene","year"])
df3

        Name  rolls     luck      scene  year
0     joshim  actor  lottery  emotional  70.0
1     kancon  funny  vitamin       real  50.0
2  bappa raj  cheka             classic   NaN

In [45]:
df3.info

<bound method DataFrame.info of         Name  rolls     luck      scene  year
0     joshim  actor  lottery  emotional  70.0
1     kancon  funny  vitamin       real  50.0
2  bappa raj  cheka             classic   NaN>

In [46]:
df3.isna().sum()

Name     0
rolls    0
luck     0
scene    0
year     1
dtype: int64

In [47]:
df3.rename(columns={"Name":"name"}, inplace=True)

In [48]:
df3

        name  rolls     luck      scene  year
0     joshim  actor  lottery  emotional  70.0
1     kancon  funny  vitamin       real  50.0
2  bappa raj  cheka             classic   NaN

In [49]:
dic= {"name": ["manna","ellias"],"character": ["danger","snakeman"], "luck": ["bad","good"], "scene":["hit", "less_dramatic"], "year": [55,65]}

In [50]:
df = pd.DataFrame(dic)

In [51]:
df

     name character  luck          scene  year
0   manna    danger   bad            hit    55
1  ellias  snakeman  good  less_dramatic    65

In [52]:
new_df = pd.concat([df,df3],ignore_index=True)

In [53]:
new_df

        name character     luck          scene  year  rolls
0      manna    danger      bad            hit  55.0    NaN
1     ellias  snakeman     good  less_dramatic  65.0    NaN
2     joshim       NaN  lottery      emotional  70.0  actor
3     kancon       NaN  vitamin           real  50.0  funny
4  bappa raj       NaN                 classic   NaN  cheka

In [54]:
import pandas as pd

df1 = pd.DataFrame({"Name": ["Alice", "Bob"], "Age": [25, 30]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"], "Age": [35, 40]})

result = pd.concat([df1, df2], axis=0)

In [55]:
df1

    Name  Age
0  Alice   25
1    Bob   30

In [56]:
df2

      Name  Age
0  Charlie   35
1    David   40

In [57]:
result

      Name  Age
0    Alice   25
1      Bob   30
0  Charlie   35
1    David   40

In [61]:
import pandas as pd
dic= {"cost":[10,15,25,30,35],
      "time": [150,200,155,225,250]}

In [62]:
df4 = DataFrame()

NameError: name 'DataFrame' is not defined

In [63]:
df

     name character  luck          scene  year
0   manna    danger   bad            hit    55
1  ellias  snakeman  good  less_dramatic    65